# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@aspect_rules_py//py:defs.bzl", _py_test = "py_test")
load("@pip_ros//:requirements.bzl", "requirement")

def _pip_ros_proxy_impl(rctx):
    """Create a pip_ros proxy repo that forwards to the real pip_ros hub.

    The real pip_ros hub is created by the pip extension in rosdistro's MODULE.bazel.
    This extension creates a proxy repository visible to rosdistro's dependent modules.
    """

    # The canonical name of the real pip_ros hub (@@rules_python++pip+pip_ros).
    # We use the canonical @@-prefixed form to avoid the proxy resolving @pip_ros
    # back to itself and causing a cycle.
    real_hub = rctx.attr.real_hub_canonical_name

    rctx.file("BUILD.bazel", """\
package(default_visibility = ["//visibility:public"])

# Ensure the `requirements.bzl` source can be accessed, since users load() from it.
exports_files(["requirements.bzl"])
""")

    # Write a requirements.bzl that re-exports everything from the real pip_ros hub
    # using its canonical @@-prefixed name to avoid self-reference cycles.
    rctx.file("requirements.bzl", """\
\"\"\"Forwarding requirements.bzl for pip_ros.

This proxy re-exports the pip_ros hub created by the rosdistro module.
@generated by rosdistro pip_ros module extension.
\"\"\"

load("@@{real_hub}//:requirements.bzl",
     _all_requirements = "all_requirements",
     _all_whl_requirements_by_package = "all_whl_requirements_by_package",
     _all_whl_requirements = "all_whl_requirements",
     _all_data_requirements = "all_data_requirements",
     _requirement = "requirement",
     _whl_requirement = "whl_requirement",
     _data_requirement = "data_requirement",
     _dist_info_requirement = "dist_info_requirement",
)

all_requirements = _all_requirements
all_whl_requirements_by_package = _all_whl_requirements_by_package
all_whl_requirements = _all_whl_requirements
all_data_requirements = _all_data_requirements

def requirement(name):
    return _requirement(name)

def whl_requirement(name):
    return _whl_requirement(name)

def data_requirement(name):
    return _data_requirement(name)

def dist_info_requirement(name):
    return _dist_info_requirement(name)
""".format(real_hub = real_hub))

_pip_ros_proxy = repository_rule(
    implementation = _pip_ros_proxy_impl,
    attrs = {
        "real_hub_canonical_name": attr.string(
            mandatory = True,
            doc = "The canonical repository name of the real pip_ros hub (without @@ prefix).",
        ),
    },
    doc = """A proxy repository that exposes the pip_ros hub to dependent modules.

This is an internal rule used by the pip_ros module extension.
""",
)

def _pip_ros_impl(ctx):
    # Find the canonical name of the real pip_ros hub. The pip_ros hub is
    # created by the pip extension and is visible to rosdistro (where this
    # extension is hosted). We get its canonical name via repo_mapping.
    #
    # The apparent name "pip_ros" in rosdistro's context maps to the canonical
    # name of the hub created by rules_python's pip extension.
    pip_ros_canonical = str(Label("@pip_ros//:_")).split("//")[0].lstrip("@")

    # Create a pip_ros proxy repository that dependent modules can use_repo().
    _pip_ros_proxy(
        name = "pip_ros",
        real_hub_canonical_name = pip_ros_canonical,
    )

# This extension exposes the pip_ros pip hub to dependent rosdistro modules.
# Dependent modules should use:
#   pip_ros = use_extension("@rosdistro//python:defs.bzl", "pip_ros")
#   use_repo(pip_ros, "pip_ros")
pip_ros = module_extension(implementation = _pip_ros_impl)

# Macro for pytest invocations.
def py_pytest(name, srcs, deps = [], args = [], **kwargs):
    _py_test(
        name = name,
        main = "@rosdistro//python:pytest_main.py",
        srcs = srcs + [
            "@rosdistro//python:pytest_main.py",
        ],
        deps = deps + [
            requirement("pytest"),
        ],
        args = args + [
            "$(location :%s)" % s
            for s in srcs
        ],
        **kwargs
    )
