# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(
    name = "rcr-examples",
)

# BCR deps

bazel_dep(name = "aspect_rules_py", version = "1.11.7")
bazel_dep(name = "llvm", version = "0.8.11")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "protobuf", version = "35.1")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_go", version = "0.60.0")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_python", version = "2.2.0")
bazel_dep(name = "rules_rs", version = "0.0.111")
bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "rules_shell", version = "0.8.0")

## RCR deps

# Load the 'perception' variant for lyrical/2026-06-08. The second patch
# release (.rcr.2) fixes an upstream rules_rs bug and adds support for
# multiple Python versions.
bazel_dep(name = "perception", version = "lyrical.2026-06-08.rcr.2")

# Make the following packages visible to this project. We use the dummy package
# version "0.0.0" to satisfy Bazel's need for a version, but be guaranteed that
# whatever is transitively imported by "ros" overrides this dummy version.
#   see: https://github.com/bazelbuild/bazel/issues/28881
bazel_dep(name = "examples_rclcpp_async_client", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_cbg_executor", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_action_client", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_action_server", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_client", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_composition", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_publisher", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_service", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_subscriber", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_minimal_timer", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_multithreaded_executor", version = "0.0.0")
bazel_dep(name = "examples_rclcpp_wait_set", version = "0.0.0")
bazel_dep(name = "examples_rclpy_executors", version = "0.0.0")
bazel_dep(name = "examples_rclpy_guard_conditions", version = "0.0.0")
bazel_dep(name = "examples_rclpy_minimal_action_client", version = "0.0.0")
bazel_dep(name = "examples_rclpy_minimal_action_server", version = "0.0.0")
bazel_dep(name = "examples_rclpy_minimal_client", version = "0.0.0")
bazel_dep(name = "examples_rclpy_minimal_publisher", version = "0.0.0")
bazel_dep(name = "examples_rclpy_minimal_service", version = "0.0.0")
bazel_dep(name = "examples_rclpy_minimal_subscriber", version = "0.0.0")
bazel_dep(name = "examples_rclpy_pointcloud_publisher", version = "0.0.0")
bazel_dep(name = "examples_tf2_py", version = "0.0.0")
bazel_dep(name = "rclcpp", version = "0.0.0")
bazel_dep(name = "rclpy", version = "0.0.0")
bazel_dep(name = "rosdistro", version = "0.0.0")
bazel_dep(name = "rosidl_core_generators", version = "0.0.0")
bazel_dep(name = "rmw_implementation", version = "0.0.0")
bazel_dep(name = "rmw_zenoh_cpp", version = "0.0.0")
bazel_dep(name = "sensor_msgs", version = "0.0.0")
bazel_dep(name = "std_msgs", version = "0.0.0")

# The C examples require rclc, which is not part of the "perception" variant.
# Nevertheless, we can bring the package in if we know its version.
bazel_dep(name = "rclc", version = "6.3.0-3.rcr.1")

## BOOTSTRAP

# Register our hermetic compiler (clang)
register_toolchains("@llvm//toolchain:all")

# Extend the hermetic macOS SDK sysroot (@llvm//extensions:osx.bzl) with the
# frameworks our dependencies needed on OSX.
osx = use_extension("@llvm//extensions:osx.bzl", "osx")
osx.frameworks(
    names = [
        "AVFAudio",
        "AVFoundation",
        "AVRouting",
        "Accelerate",
        "AppKit",
        "ApplicationServices",
        "AudioToolbox",
        "CFNetwork",
        "CloudKit",
        "Cocoa",
        "ColorSync",
        "CoreAudio",
        "CoreAudioTypes",
        "CoreData",
        "CoreFoundation",
        "CoreGraphics",
        "CoreImage",
        "CoreLocation",
        "CoreMIDI",
        "CoreMedia",
        "CoreServices",
        "CoreText",
        "CoreVideo",
        "DiskArbitration",
        "FontServices",
        "Foundation",
        "IOKit",
        "IOSurface",
        "ImageIO",
        "Kernel",
        "MediaToolbox",
        "Metal",
        "OSLog",
        "OpenGL",
        "PrintCore",
        "QuartzCore",
        "Security",
        "Symbols",
        "SystemConfiguration",
        "UniformTypeIdentifiers",
        "_LocationEssentials",
    ],
)

# Python / pip

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.12",
)

pip_ros = use_extension("@rosdistro//python:defs.bzl", "pip_ros")
use_repo(pip_ros, "pip_ros")

# Rust / crates

rs_toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")
rs_toolchains.toolchain(
    edition = "2021",
    version = "1.93.0",
)
use_repo(rs_toolchains, "default_rust_toolchains")

register_toolchains(
    "@default_rust_toolchains//...",
)
